version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tienda
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_AUTHENTICATION_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_tienda:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  app:
    container_name: app
    restart: always
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017/tienda?authSource=admin'
      MONGODB_USER: admin
      MONGODB_PASSWORD: password
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - '80:3000'
    depends_on:
      - mongodb
volumes:
  mongodb_tienda:
  
